version: "3.2"

services:
  node:
    container_name: spin-node
    image: node:8-alpine
    command: sh -c "yarn config set workspaces-experimental true && yarn && sh"
    stdin_open: true
    tty: true
    working_dir: /var/spin
    volumes:
      - type: bind
        source: ./
        target: /var/spin

  nginx:
    container_name: spin-nginx
    image: nginx:1-alpine
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./docker/nginx/dev.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./
        target: /var/spin

  selenium:
    container_name: spin-selenium
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
